apiVersion: v1
kind: Service
metadata:
  name: webook-live
spec:
#  ClusterIP
  type: LoadBalancer
  selector:
    app: webook-live
  ports:
    - protocol: TCP
      name: http
      port: 8081
      targetPort: 8081

  